---
driver:
  name: vagrant
  synced_folders:
    - ["test/dummy", "/home/vagrant/service", "create: true"]

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[dude::default]
    attributes:
      dude:
        run_as_user: vagrant
        install_dir: /home/vagrant/service
